name: Bestium
version: '${version}'
main: cz.jeme.bestium.BestiumPlugin
bootstrapper: cz.jeme.bestium.BestiumBootstrapper
api-version: '${minecraftVersion}'
author: Hužva
description: A powerful library plugin for creating Minecraft entities with custom behavior
load: STARTUP
dependencies:
  server:
    BetterModel:
      load: BEFORE
      required: false
      join-classpath: true
    Nova:
      required: false
      join-classpath: false

permissions:
  bestium.command:
    default: op
    children:
      bestium.command.summon: true
      bestium.command.spawnegg: true