name: Bestium
version: '${version}'
main: cz.jeme.bestium.core.BestiumImpl
bootstrapper: cz.jeme.bestium.core.BestiumBootstrapper
api-version: '${minecraftVersion}'
author: Hužva
description: A powerful library plugin for creating Minecraft entities with custom behavior.
load: STARTUP
dependencies:
  server:
    BetterModel:
      load: BEFORE
      required: true
      join-classpath: true