name: Deploy javadoc

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Generate API javadoc
        run: ./gradlew api:javadoc

      - name: Obtain project version
        id: obtain_version
        run: |
          version=$(./gradlew -q printVersion)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './api/build/docs/javadoc'
          destination_dir: ${{ steps.obtain_version.outputs.version }}
          cname: jd.bestium.jeme.cz