name: Deploy Bestium docs to GitHub Pages

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
    paths:
      - 'docs/**'
      - 'api/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 20 ]
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Generate API Javadoc
        run: ./gradlew api:javadoc

      - name: Copy API Javadoc
        run: |
          mkdir -p docs/public/jd
          cp -r api/build/docs/javadoc/* docs/public/jd/

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./docs/pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: ./docs

      - name: Build Astro
        run: pnpm run build
        working-directory: ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './docs/dist'